import type { NextPage } from 'next'
import { useState } from 'react'
import { useInput } from '../hooks/inputHook'
import Head from 'next/head'

/**
 * The home page for users to generate the shortened url
 * @returns {JSX.Element}
 */
const Home: NextPage = () => {
  const { value, bind, reset } = useInput('')
  const [ result, setResult ] = useState('')

  /**
   * The regex for website checking
   */
  const re = /[(http(s)?):\/\/(www\.)?a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/

  const handleSubmit = async (e : any) => {
    e.preventDefault();
    if (!re.test(value)) {
      alert("This is not a valid website!")
    } else {
      
      /**
       * Removes the 'http://' or 'https://' for processing
       */
      let url : string = value.replace(/^(?:f|ht)tps?\:\/\//, "")
      console.log(url)
      const res = await fetch('/api/n/' + url)
      .then(res => {
        return res.json()
      })
      setResult(res.new)
      reset();
    }
  }

  return (
    <div className="flex flex-col w-screen justify-center align-center items-center bg-gray-900 text-gray-300">
      <Head>
        <title>Zefr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col container justify-center align-center items-center">
        <div className="flex flex-col container justify-center min-h-screen align-center items-center" >
          <form className="flex flex-col container justify-center align-center items-center" onSubmit={handleSubmit}>
            <label>Url to shorten</label>
            <input className="border-b-2 border-solid bg-gray-900 text-gray-300 max-w-md text-center" type="text" {...bind} />
            <br />
            <button className="border-solid border-2 p-1" type="submit">Shorten</button>
          </form>
          <br />
          <div>
            <p className="text-gray-300">{'> ' + result + ' <'}</p>
          </div>
          <footer>
            Made by <a href="http://cassie.id">Cassie C</a>
          </footer>
        </div>
      </main>
    </div>
  )
}

export default Home
