import type { NextPage } from 'next'
import { useState } from 'react'
import { useInput } from '../hooks/inputHook'
import Head from 'next/head'

const Home: NextPage = () => {
  const { value, bind, reset } = useInput('')
  const { result, setResult } = useState(0)
  const re = /[(http(s)?):\/\/(www\.)?a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/

  let url : string = ""

  const handleSubmit = async (e : any) => {
    e.preventDefault();
    if (!re.test(value)) {
      alert("This is not a valid website!")
    } else {
      const res = await fetch('/api/n/'+value)
      .then(res => {
        return res.json()
      })
      console.log(res.new)
      url = res.new
      reset();
    }
  }

  const handleReveal = () => setResult(url)


  return (
    <div className="flex flex-col w-screen justify-center align-center items-center bg-gray-900 text-gray-300">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col container justify-center align-center items-center">
        <div className="flex flex-col container justify-center min-h-screen align-center items-center" >
          <form className="flex flex-col container justify-center align-center items-center" onSubmit={handleSubmit}>
            <label>Url to shorten</label>
            <input className="border-b-2 border-solid bg-gray-900 text-gray-300 max-w-md" type="text" {...bind} />
            <br />
            <button className="border-solid border-2 p-1" type="submit">Shorten</button>
          </form>
          <br />
          <button className="border-solid border-2 p-1" type="submit" onClick={handleReveal}>Show Short</button>
          <br />
          <div>{result}</div>
        </div>
      </main>

      <footer>
        
      </footer>
    </div>
  )
}

export default Home
